config:
    run_cases: [sod1, sod2]  # or simply: all
    
    global:
        solver: godunov
        riemann_solver: exact
        reconstruction: P0
        time_integrator: euler
        left_boundary: free_stream
        right_boundary: free_stream

        N: 1000
        cfl: 0.5
        padding: 2
        gamma: 1.4
        dim: 1
        L_x: 1
        L_y: 1
        L_z: 1

        Q_user: 2

        x0: 0.5
        analytical: true

        t_end: 0.25
        step_end: 0

        log_every_steps: 50
        log_every_time: 0.0

        output_every_steps: 50
        output_every_time: 0.0
        
        output_formats: [vtk, png, gif2560x1600]
        output_dir: "../result"

    # Each case can override any global setting
    cases:
        sod1:
            rho_L: 1.0
            u_L: 0.0
            P_L: 1.0
            rho_R: 0.125
            u_R: 0.0
            P_R: 0.1

            x0: 0.5
            t_end: 0.25
        
        sod2:
            rho_L: 1.0
            u_L: -2.0
            P_L: 0.4
            rho_R: 1.0
            u_R: 2.0
            P_R: 0.4

            x0: 0.5
            t_end: 0.15
        
        sod3:
            rho_L: 1.0
            u_L: 0.0
            P_L: 1000.0
            rho_R: 1.0
            u_R: 0.0
            P_R: 0.01

            x0: 0.5
            t_end: 0.012
        
        sod4:
            rho_L: 1.0
            u_L: 0.0
            P_L: 0.01
            rho_R: 1.0
            u_R: 0.0
            P_R: 100.0

            x0: 0.5
            t_end: 0.035
        
        sod5:
            rho_L: 5.99924
            u_L: 19.5975
            P_L: 460.894
            rho_R: 5.99242
            u_R: -6.19633
            P_R: 46.0950

            x0: 0.5
            t_end: 0.035
